name: Run ETL Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at 12 AM UTC
  workflow_dispatch:      # (Optional) Allows manual trigger from GitHub UI

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ETL script
        env:
          GNEWS_API: ${{ secrets.GNEWS_API }}
          GEMINI_API: ${{ secrets.GEMINI_API_4 }}
          POSTGRESQL_API: ${{ secrets.NEON_DATABASE }}
        run: |
          python etl/etl.py
